import { NextRequest, NextResponse } from "next/server";

export async function GET(request: NextRequest) {
  // Mock profile data
  const mockUsers = [
    {
      communication: {
        call: "41763490644",
        email: "charlotte.coat@fertas.ch",
        sms: "41763490644",
        email_to_text: "41763490644",
      },
      email: "charlotte.coat@fertas.ch",
      enabled: true,
      id: 1955,
      role_level: 1,
      username: "charlotte.coat@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "josefina.vargas@cpma.ch",
        sms: null,
        email_to_text: null,
      },
      email: "josefina.vargas@cpma.ch",
      enabled: true,
      id: 1971,
      role_level: 1,
      username: "josefina.vargas@cpma.ch",
    },
    {
      communication: {
        call: "0041792954407",
        email: "anne.krattinger@fertas.ch",
        sms: "0041792954407",
        email_to_text: "0041792954407",
      },
      email: "anne.krattinger@fertas.ch",
      enabled: true,
      id: 2200,
      role_level: 1,
      username: "anne.krattinger@fertas.ch",
    },
    {
      communication: {
        call: "41774228442",
        email: "carla.vieiradacosta@fertas.ch",
        sms: "41774228442",
        email_to_text: "41774228442",
      },
      email: "carla.vieiradacosta@fertas.ch",
      enabled: true,
      id: 2439,
      role_level: 1,
      username: "carla.vieiradacosta@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "Audrey.Henriet@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "Audrey.Henriet@fertas.ch",
      enabled: true,
      id: 2461,
      role_level: 1,
      username: "Audrey.Henriet@fertas.ch",
    },
    {
      communication: {
        call: "41762376890",
        email: "veronique.vallet@fertas.ch",
        sms: "41762376890",
        email_to_text: "41762376890",
      },
      email: "veronique.vallet@fertas.ch",
      enabled: true,
      id: 2503,
      role_level: 1,
      username: "veronique.vallet@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "fecoffey@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "fecoffey@fertas.ch",
      enabled: true,
      id: 2523,
      role_level: 1,
      username: "fecoffey@fertas.ch",
    },
    {
      communication: {
        call: "41764180613",
        email: "pedro.oliveira@fertas.ch",
        sms: "41764180613",
        email_to_text: "41764180613",
      },
      email: "pedro.oliveira@fertas.ch",
      enabled: true,
      id: 2557,
      role_level: 1,
      username: "Oliveira",
    },
    {
      communication: {
        call: null,
        email: "antonella.desimone@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "antonella.desimone@fertas.ch",
      enabled: true,
      id: 2701,
      role_level: 1,
      username: "antonella.desimone@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "josefina.vargas@fertas.ch",
        sms: "41787896387",
        email_to_text: "41787896387",
      },
      email: "josefina.vargas@fertas.ch",
      enabled: true,
      id: 2885,
      role_level: 1,
      username: "josefina.vargas@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "sabrina.cugini@cpma.ch",
        sms: null,
        email_to_text: null,
      },
      email: "sabrina.cugini@cpma.ch",
      enabled: true,
      id: 3192,
      role_level: 1,
      username: "sabrina.cugini@cpma.ch",
    },
    {
      communication: {
        call: "41797099286",
        email: "celine.leyvraz@fertas.ch",
        sms: "41797099286",
        email_to_text: "41797099286",
      },
      email: "celine.leyvraz@fertas.ch",
      enabled: true,
      id: 3215,
      role_level: 1,
      username: "celine.leyvraz@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "fabien.murisier@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "fabien.murisier@fertas.ch",
      enabled: true,
      id: 3375,
      role_level: 1,
      username: "fabien.murisier@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "carine.nzolameso@cpma.ch",
        sms: null,
        email_to_text: null,
      },
      email: "carine.nzolameso@cpma.ch",
      enabled: true,
      id: 3417,
      role_level: 1,
      username: "CMNZOLAMESO",
    },
    {
      communication: {
        call: null,
        email: "dan.maerki@gmail.com ",
        sms: null,
        email_to_text: null,
      },
      email: "dan.maerki@gmail.com ",
      enabled: true,
      id: 4129,
      role_level: 1,
      username: "daniel_gmail",
    },
    {
      communication: {
        call: "0041786068397",
        email: "antonella.biondo@fertas.ch",
        sms: "0041786068397",
        email_to_text: "0041786068397",
      },
      email: "antonella.biondo@fertas.ch",
      enabled: true,
      id: 4454,
      role_level: 1,
      username: "antonella.biondo@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "valerie.mangeat@ne.ch",
        sms: null,
        email_to_text: null,
      },
      email: "valerie.mangeat@ne.ch",
      enabled: true,
      id: 1973,
      role_level: 2,
      username: "valerie.mangeat@ne.ch",
    },
    {
      communication: {
        call: "41794357869",
        email: "lara.campa@fertas.ch",
        sms: "41794357869",
        email_to_text: "41794357869",
      },
      email: "lara.campa@fertas.ch",
      enabled: true,
      id: 3075,
      role_level: 2,
      username: "lara.campa@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "laurence.angeloz@fertas.ch",
        sms: "41795895492",
        email_to_text: "41795895492",
      },
      email: "laurence.angeloz@fertas.ch",
      enabled: true,
      id: 3085,
      role_level: 2,
      username: "laurence.angeloz@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "olivier.charles@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "olivier.charles@fertas.ch",
      enabled: true,
      id: 3199,
      role_level: 2,
      username: "olivier.charles@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "maite.monbaron@cpma.ch",
        sms: null,
        email_to_text: null,
      },
      email: "maite.monbaron@cpma.ch",
      enabled: true,
      id: 3324,
      role_level: 2,
      username: "maite.monbaron@cpma.ch",
    },
    {
      communication: {
        call: null,
        email: "Virginie.Yalak@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "Virginie.Yalak@fertas.ch",
      enabled: true,
      id: 3354,
      role_level: 2,
      username: "Virginie.Yalak@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "stephanie.pretot@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "stephanie.pretot@fertas.ch",
      enabled: true,
      id: 3887,
      role_level: 2,
      username: "stephanie.pretot@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "laury.exty@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "laury.exty@fertas.ch",
      enabled: true,
      id: 3914,
      role_level: 2,
      username: "laury.exty@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "severine.sacchetti@ne.ch",
        sms: null,
        email_to_text: null,
      },
      email: "severine.sacchetti@ne.ch",
      enabled: true,
      id: 3943,
      role_level: 2,
      username: "severine.sacchetti@ne.ch",
    },
    {
      communication: {
        call: null,
        email: "info@fertas.ch",
        sms: null,
        email_to_text: null,
      },
      email: "info@fertas.ch",
      enabled: true,
      id: 4320,
      role_level: 2,
      username: "Info@fertas.ch",
    },
    {
      communication: {
        call: null,
        email: "amelie.rebois@cpma.ch",
        sms: null,
        email_to_text: null,
      },
      email: "amelie.rebois@cpma.ch",
      enabled: true,
      id: 4339,
      role_level: 2,
      username: "amelie.rebois@cpma.ch",
    },
  ];
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 100));

  return NextResponse.json(mockUsers);
}
