// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StyleProvider, QueryProvider } from "@/styles/provider";
import { AuthProvider } from "@/contexts/AuthContext";
import { BackendProvider } from '@/contexts/BackendContext';
import { AlarmProvider } from '@/contexts/AlarmContext';
import { ProfileProvider } from '@/contexts/ProfileContext';
import { AlarmProfileProvider } from "@/contexts/AlarmProfileContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aginova CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BackendProvider>
          <QueryProvider>
            <StyleProvider>
              <AuthProvider>
                <ProfileProvider>
                  <AlarmProvider>
                    <AlarmProfileProvider>
                      {children}
                    </AlarmProfileProvider>
                  </AlarmProvider>
                </ProfileProvider>
              </AuthProvider>
            </StyleProvider>
          </QueryProvider>
        </BackendProvider>
      </body>
    </html>
  );
}
