import { NextRequest, NextResponse } from "next/server";

// Mock data for alarm notifications
const mockAlarmNotifications = {
  data: [
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1339,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 1,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "SASES@chop.edu",
        alert_email_to_text: "2152526625@tmomail.net",
        alert_sms: "12152526625",
      },
      user_email: "SASES@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1340,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 1,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "SASES@chop.edu",
        alert_email_to_text: "2152526625@tmomail.net",
        alert_sms: "12152526625",
      },
      user_email: "SASES@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1341,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 2,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "napitp@chop.edu",
        alert_email_to_text: "3185473395@vtext.com",
        alert_sms: null,
      },
      user_email: "napitp@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1342,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 2,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "napitp@chop.edu",
        alert_email_to_text: "3185473395@vtext.com",
        alert_sms: null,
      },
      user_email: "napitp@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1343,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 3,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "TAKANOHASA@chop.edu",
        alert_email_to_text: "3012339392@vtext.com",
        alert_sms: "13012339392",
      },
      user_email: "TAKANOHASA@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1344,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 3,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "TAKANOHASA@chop.edu",
        alert_email_to_text: "3012339392@vtext.com",
        alert_sms: "13012339392",
      },
      user_email: "TAKANOHASA@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1345,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 4,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "bhagavatua@chop.edu",
        alert_email_to_text: "7164447144@txt.att.net",
        alert_sms: "17164447144",
      },
      user_email: "bhagavatua@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1346,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 4,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "bhagavatua@chop.edu",
        alert_email_to_text: "7164447144@txt.att.net",
        alert_sms: "17164447144",
      },
      user_email: "bhagavatua@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1347,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 5,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "houz@chop.edu",
        alert_email_to_text: "4012099331@txt.att.net",
        alert_sms: "14012099331",
      },
      user_email: "houz@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1348,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 5,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "houz@chop.edu",
        alert_email_to_text: "4012099331@txt.att.net",
        alert_sms: "14012099331",
      },
      user_email: "houz@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1349,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 6,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "WANGX11@chop.edu",
        alert_email_to_text: "2158709687@vtext.com",
        alert_sms: "12158709687",
      },
      user_email: "WANGX11@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1350,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 6,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "WANGX11@chop.edu",
        alert_email_to_text: "2158709687@vtext.com",
        alert_sms: "12158709687",
      },
      user_email: "WANGX11@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1351,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 7,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "digiovanno@chop.edu",
        alert_email_to_text: null,
        alert_sms: "16103315886",
      },
      user_email: "digiovanno@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1352,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 7,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "digiovanno@chop.edu",
        alert_email_to_text: null,
        alert_sms: "16103315886",
      },
      user_email: "digiovanno@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 128,
      escalation_level: 1,
      id: 1353,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 8,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "lelej@chop.edu",
        alert_email_to_text: null,
        alert_sms: "17169708381",
      },
      user_email: "lelej@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 128,
      escalation_level: 1,
      id: 1354,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 8,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "lelej@chop.edu",
        alert_email_to_text: null,
        alert_sms: "17169708381",
      },
      user_email: "lelej@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1355,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 1,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "SASES@chop.edu",
        alert_email_to_text: "2152526625@tmomail.net",
        alert_sms: "12152526625",
      },
      user_email: "SASES@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1356,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 1,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "SASES@chop.edu",
        alert_email_to_text: "2152526625@tmomail.net",
        alert_sms: "12152526625",
      },
      user_email: "SASES@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1357,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 2,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "TAKANOHASA@chop.edu",
        alert_email_to_text: "3012339392@vtext.com",
        alert_sms: "13012339392",
      },
      user_email: "TAKANOHASA@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1358,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 2,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "TAKANOHASA@chop.edu",
        alert_email_to_text: "3012339392@vtext.com",
        alert_sms: "13012339392",
      },
      user_email: "TAKANOHASA@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1359,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 3,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "napitp@chop.edu",
        alert_email_to_text: "3185473395@vtext.com",
        alert_sms: null,
      },
      user_email: "napitp@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1360,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 3,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "napitp@chop.edu",
        alert_email_to_text: "3185473395@vtext.com",
        alert_sms: null,
      },
      user_email: "napitp@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1361,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 4,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "bhagavatua@chop.edu",
        alert_email_to_text: "7164447144@txt.att.net",
        alert_sms: "17164447144",
      },
      user_email: "bhagavatua@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1362,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 4,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "bhagavatua@chop.edu",
        alert_email_to_text: "7164447144@txt.att.net",
        alert_sms: "17164447144",
      },
      user_email: "bhagavatua@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1363,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 5,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "houz@chop.edu",
        alert_email_to_text: "4012099331@txt.att.net",
        alert_sms: "14012099331",
      },
      user_email: "houz@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1364,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 5,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "houz@chop.edu",
        alert_email_to_text: "4012099331@txt.att.net",
        alert_sms: "14012099331",
      },
      user_email: "houz@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1365,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 6,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "WANGX11@chop.edu",
        alert_email_to_text: "2158709687@vtext.com",
        alert_sms: "12158709687",
      },
      user_email: "WANGX11@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1366,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 6,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "WANGX11@chop.edu",
        alert_email_to_text: "2158709687@vtext.com",
        alert_sms: "12158709687",
      },
      user_email: "WANGX11@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1367,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 7,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "digiovanno@chop.edu",
        alert_email_to_text: null,
        alert_sms: "16103315886",
      },
      user_email: "digiovanno@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1368,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 7,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "digiovanno@chop.edu",
        alert_email_to_text: null,
        alert_sms: "16103315886",
      },
      user_email: "digiovanno@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 129,
      escalation_level: 2,
      id: 1369,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 8,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "lelej@chop.edu",
        alert_email_to_text: null,
        alert_sms: "17169708381",
      },
      user_email: "lelej@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 129,
      escalation_level: 2,
      id: 1370,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 8,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "lelej@chop.edu",
        alert_email_to_text: null,
        alert_sms: "17169708381",
      },
      user_email: "lelej@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1371,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 1,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "SASES@chop.edu",
        alert_email_to_text: "2152526625@tmomail.net",
        alert_sms: "12152526625",
      },
      user_email: "SASES@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1372,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 1,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "SASES@chop.edu",
        alert_email_to_text: "2152526625@tmomail.net",
        alert_sms: "12152526625",
      },
      user_email: "SASES@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1373,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 2,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "TAKANOHASA@chop.edu",
        alert_email_to_text: "3012339392@vtext.com",
        alert_sms: "13012339392",
      },
      user_email: "TAKANOHASA@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1374,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 2,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "TAKANOHASA@chop.edu",
        alert_email_to_text: "3012339392@vtext.com",
        alert_sms: "13012339392",
      },
      user_email: "TAKANOHASA@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1375,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 3,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "napitp@chop.edu",
        alert_email_to_text: "3185473395@vtext.com",
        alert_sms: null,
      },
      user_email: "napitp@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1376,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 3,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "napitp@chop.edu",
        alert_email_to_text: "3185473395@vtext.com",
        alert_sms: null,
      },
      user_email: "napitp@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1377,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 4,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "bhagavatua@chop.edu",
        alert_email_to_text: "7164447144@txt.att.net",
        alert_sms: "17164447144",
      },
      user_email: "bhagavatua@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1378,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 4,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "bhagavatua@chop.edu",
        alert_email_to_text: "7164447144@txt.att.net",
        alert_sms: "17164447144",
      },
      user_email: "bhagavatua@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1379,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 5,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "houz@chop.edu",
        alert_email_to_text: "4012099331@txt.att.net",
        alert_sms: "14012099331",
      },
      user_email: "houz@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1380,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 5,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "houz@chop.edu",
        alert_email_to_text: "4012099331@txt.att.net",
        alert_sms: "14012099331",
      },
      user_email: "houz@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1381,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 6,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "WANGX11@chop.edu",
        alert_email_to_text: "2158709687@vtext.com",
        alert_sms: "12158709687",
      },
      user_email: "WANGX11@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1382,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 6,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "WANGX11@chop.edu",
        alert_email_to_text: "2158709687@vtext.com",
        alert_sms: "12158709687",
      },
      user_email: "WANGX11@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1383,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 7,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "digiovanno@chop.edu",
        alert_email_to_text: null,
        alert_sms: "16103315886",
      },
      user_email: "digiovanno@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1384,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 7,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "digiovanno@chop.edu",
        alert_email_to_text: null,
        alert_sms: "16103315886",
      },
      user_email: "digiovanno@chop.edu",
    },
    {
      alert_channel: "email",
      escalation_id: 130,
      escalation_level: 3,
      id: 1385,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 8,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "lelej@chop.edu",
        alert_email_to_text: null,
        alert_sms: "17169708381",
      },
      user_email: "lelej@chop.edu",
    },
    {
      alert_channel: "sms",
      escalation_id: 130,
      escalation_level: 3,
      id: 1386,
      receiver_list_id: null,
      receiver_list_user_contacts: [],
      receiver_scope: "individual",
      receiver_type: "user",
      repetition: 8,
      sensor_id: null,
      sent_at: "2025-08-08T14:00:35.052130+00:00",
      user_contact: {
        alert_call: null,
        alert_email: "lelej@chop.edu",
        alert_email_to_text: null,
        alert_sms: "17169708381",
      },
      user_email: "lelej@chop.edu",
    },
  ],
};

export async function GET(request: NextRequest, context: any) {
  try {
    const alarmId = context.params.id;

    // In a real implementation, you would fetch this data from your backend
    // For now, we'll return mock data
    const notifications = mockAlarmNotifications;

    return NextResponse.json(notifications);
  } catch (error) {
    console.error("Error fetching alarm notifications:", error);
    return NextResponse.json(
      { error: "Failed to fetch alarm notifications" },
      { status: 500 }
    );
  }
}
